### PR TITLE
Send emails to Jonni and Albertinin on CI failures

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Email triggered, although the email service configured in Jenkins is not working

screen shot 2018-05-23 at 00 33 38

I'd review + merge this PR, because once the email configuration is fixed, everything will work

cc/ @pragmaticivan

**Comment by pragmaticivan** [comment]
What's missing on e-mail configuration? I don't see a reason to merge it if it's not working yet.

**Comment by mdelapenya** [comment]
Email provider configured with sendgrid and it works

**Comment by mdelapenya** [comment]
Closing, as it has been sent here #26

**Pull request closed without merging**
